version: '3.9'

services: 
   
    api:
        build: .
        image: api-mandalorian-episodes
        ports: 
            - "5000:5000"
        links:
            - db:db
    
    db:
        image: redis
        ports:
            - "6379:6379"